name: 构建并发布内核

permissions:
  contents: write
  actions: write
  
on:
  workflow_dispatch:
    inputs:
      version:
        description: '自定义后缀(6.1.141-android14-11-g<自动HASH>-<后缀>/留空则无-后缀)'
        required: false
        type: string
jobs:

  build-kernel:
    uses: ./.github/workflows/build-kernel.yml
    secrets: inherit
    with:
      version: ${{ inputs.version }}

  trigger-release:
    runs-on: ubuntu-latest
    needs:
      - build-kernel
    env:
      REPO_NAME: 6.1-LTS-GKI-Kernel-Action
      GH_TOKEN: ${{ github.token }}
      RELEASE_NAME: "GKI 6.1.LTS SukiSU"
      RELEASE_BODY:
    steps:
      - name: 检查代码
        uses: actions/checkout@v4

      - name: 获取提交哈希值并生成提交URL
        run: |
          GITLAB_OWNER="simonpunk"
          GITLAB_REPO="susfs4ksu"
          
          declare -A BRANCH_MAP=(
            ["gki_android14_6_1"]="gki-android14-6.1"
          )
          
          for var_name in "${!BRANCH_MAP[@]}"; do
            branch_name="${BRANCH_MAP[$var_name]}"
            COMMIT_HASH=$(git ls-remote https://gitlab.com/$GITLAB_OWNER/$GITLAB_REPO.git refs/heads/$branch_name | awk '{ print $1 }')
            
            if [[ -n "$COMMIT_HASH" ]]; then
              COMMIT_URL="https://gitlab.com/$GITLAB_OWNER/$GITLAB_REPO/-/commit/$COMMIT_HASH"
              echo "$branch_name Commit: $COMMIT_HASH"
              echo "$branch_name Commit URL: $COMMIT_URL"
              
              echo "COMMIT_HASH_${var_name}=$COMMIT_HASH" >> "$GITHUB_ENV"
              echo "COMMIT_URL_${var_name}=$COMMIT_URL" >> "$GITHUB_ENV"
            fi
          done

          BRANCH="${{ inputs.kernelsu_branch }}"
      
          get_ref() {
            local name="$1" repo="$2" path="$3" mode="$4"
            if [[ "$mode" == "tag" ]]; then
              ref=$(git ls-remote --tags --sort=-v:refname "$repo" | grep -o 'refs/tags/.*' | cut -d/ -f3 | head -n1)
              url="https://github.com/$path/releases/tag/$ref"
            else
              ref=$(git ls-remote "$repo" HEAD | awk '{print $1}')
              url="https://github.com/$path/commit/$ref"
            fi
            echo "SukiSU_REF=$ref" >> $GITHUB_ENV
            echo "SukiSU_URL=$url" >> $GITHUB_ENV
          }
      
          [[ "$BRANCH" == "Stable" ]] && MODE="tag" || MODE="commit"
      
          get_ref "SukiSU Ultra" "https://github.com/ShirkNeko/SukiSU-Ultra.git" "ShirkNeko/SukiSU-Ultra" "$MODE"

      - name: 创建新标签
        run: |
            LATEST_TAG=$(gh api repos/${{ github.repository }}/tags --jq '.[0].name')
            if [ -z "$LATEST_TAG" ]; then
              LATEST_TAG="6.1-LTS-v0"
            fi
            
            NEW_TAG=$(echo "$LATEST_TAG" | awk -F'-v' '{suffix=$2; if (!suffix) suffix=0; suffix++; printf "%s-v%d", $1, suffix}')
    
            echo "新标签: $NEW_TAG"
            echo "NEW_TAG=${NEW_TAG}" >> $GITHUB_ENV

            git tag $NEW_TAG
            git push origin $NEW_TAG

      - name: 下载附件
        uses: actions/download-artifact@v4
        with:
          path: ./downloaded-artifacts

      - name: 设置 Release 内容
        run: |
          cat << 'EOF' > release_body.md
          
          ### 功能:
          -> SUSFS v1.5.8(最新)
          -> VFS Hooks 隐藏支持
          -> Magic Mount 支持
          -> Wireguard 支持
          -> LZ4KD & BBR 支持
          -> LZ4-1.10(armv8优化)
          -> 更新 ZSTD-1.7 版本
          -> LTS 分支小米系修复
          -> 开启 -O2 编译优化
          -> Zyc Clang21 编译
      
          ### 发布提交Hash:
          -> SukiSU Ultra: [${{ env.SukiSU_REF }}](${{ env.SukiSU_REF }})
          -> SUSFS(GKI-6.1):[${{ env.COMMIT_HASH_gki_android14_6_1 }}](${{ env.COMMIT_URL_gki_android14_6_1 }})
          EOF

      - name: 设置 Release 标题
        run: |
          git clone https://github.com/SukiSU-Ultra/SukiSU-Ultra.git
          cd SukiSU-Ultra
          KSU_GIT_VERSION=$(git rev-list --count HEAD)
          KSU_VERSION=$((10000 + KSU_GIT_VERSION + 700))
          echo $KSU_VERSION
          echo "RELEASE_NAME=${{ env.RELEASE_NAME }}($KSU_VERSION)" >> $GITHUB_ENV

      - name: 创建 GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEW_TAG }}
          prerelease: ${{ inputs.release_type == 'Pre-Release' }}
          files: ""
          name: ${{ env.RELEASE_NAME }}
          body_path: release_body.md

      - name: 上传编译产出文件到 Release
        run: |
          for file in ./downloaded-artifacts/*-kernel-*/*; do
            if [ -d "$file" ]; then
              continue
            fi
            echo "Uploading $file..."
            gh release upload ${{ env.NEW_TAG }} "$file"
          done

      - name: 显示上传的文件
        run: |
          echo "GitHub release created with the following files:"
          ls ./downloaded-artifacts/**/*