name: Build-Kernel-6.1-LTS
permissions:
  contents: write
  actions: write

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string

jobs:
  build-kernel-sukisu-susfs:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CCACHE_MAXSIZE: "8G"
      KBUILD_BUILD_USER: "DawnFz"
      KBUILD_BUILD_HOST: "Github"
      CONFIG: "android14-6.1-LTS"
      GOOGLE_SOURCE_URL: "https://android.googlesource.com"

    steps:
      - name: 初始化构建空间
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          swap-size-mb: 8192
          remove-dotnet: "true"
          remove-haskell: "true"
          remove-codeql: "true"

      - name: 克隆外部依赖
        run: |
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android14-6.1 --depth 1
          git clone https://github.com/ShirkNeko/SukiSU_patch.git --depth 1
          git clone https://${{ secrets.PATCH_ACCESS_TOKEN }}@github.com/OgayCn/Kernel-Patch.git --depth 1 kernel-patch
          cd kernel-patch
          cp -r AnyKernel3 ../

      - name: 配置环境变量
        id: set-variable
        run: |
          CHASH=$(date +%s%N | sha1sum | cut -c1-12)
          echo "本次构建哈希:$CHASH"
          echo "CCACHE_DIR=$HOME/.ccache_6.1.lts" >> $GITHUB_ENV
          echo "BOOTHASH=$CHASH" >> $GITHUB_ENV
          TIMESTAMP=$(date -u '+%a %b %e %T %Z %Y')
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

          NOW_HOUR=$(TZ=Asia/Shanghai date +%H)
          DATE_STR=$(TZ=Asia/Shanghai date +%Y%m%d)

          if [ "$NOW_HOUR" -lt 18 ]; then
            CCACHE_DATETIME="${DATE_STR}00"
          else
            CCACHE_DATETIME="${DATE_STR}18"
          fi

          echo "使用的 CCACHE_DATETIME: $CCACHE_DATETIME"
          echo "CCACHE_DATETIME=$CCACHE_DATETIME" >> $GITHUB_OUTPUT

      - name: 安装环境依赖
        run: |
          sudo apt update -qq
          sudo apt install -y --no-install-recommends \
            python3 git curl ccache libelf-dev \
            build-essential flex bison libssl-dev \
            libncurses-dev liblz4-tool zlib1g-dev \
            libxml2-utils rsync unzip

      - name: 载入 ccache 缓存
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os }}-${{ github.ref }}-${{ steps.set-variable.outputs.CCACHE_DATETIME }}
          restore-keys: |
            ccache-${{ runner.os }}-${{ github.ref }}-${{ steps.set-variable.outputs.CCACHE_DATETIME }}-

      - name: 初始化 cceche
        run: |
          INIT_FLAG="$CCACHE_DIR/.ccache_initialized"
          if command -v ccache >/dev/null 2>&1; then
            if [ ! -f "$INIT_FLAG" ]; then
              echo "init ccache ($CCACHE_DIR)..."
              mkdir -p "$CCACHE_DIR"
              ccache -M "$CCACHE_MAXSIZE"
              touch "$INIT_FLAG"
            fi
          fi

      - name: 同步内核源码
        run: |
          mkdir -p ./git-repo
          curl https://storage.googleapis.com/git-repo-downloads/repo > ./git-repo/repo
          chmod a+rx ./git-repo/repo
          mkdir -p "$CONFIG"
          cd "$CONFIG"
          $GITHUB_WORKSPACE/./git-repo/repo init --depth=1 --u $GOOGLE_SOURCE_URL/kernel/manifest -b common-android14-6.1-lts --repo-rev=v2.16
          $GITHUB_WORKSPACE/./git-repo/repo --trace sync -c -j$(nproc --all) --no-tags --fail-fast

      - name: 下载 Clang 21
        run: |
          CLANG_LINK=$(curl -sL https://raw.githubusercontent.com/ZyCromerZ/Clang/main/Clang-main-link.txt)
          #curl -L -o clang-22.tar.gz "https://github.com/ZyCromerZ/Clang/releases/download/22.0.0git-20250716-release/Clang-22.0.0git-20250716.tar.gz"
          curl -L -o clang-22.tar.gz "$CLANG_LINK"

          # 解压并清理
          echo "Unzip clang-22"
          sudo mkdir -p $GITHUB_WORKSPACE/clang-22
          sudo tar -xzf clang-22.tar.gz -C $GITHUB_WORKSPACE/clang-22
          sudo rm -f clang-22.tar.gz
      
      - name: 添加 SukiSU
        run: |
          echo "开始安装 SukiSU Ultra..."
          cd "$CONFIG"
          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main

          #echo "开始安装 SukiSU Ultra..."
          #cd "$CONFIG"
          #curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main
          #cd KernelSU
          #git checkout b8b75349e01d2cfa00496b72795bb185b9c2ae4b
          #cd ..

      - name: 应用内核补丁
        run: |
          cd "$CONFIG"
          # Copy SUSFS patches
          cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1.patch ./common/
          cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/
          cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/

          # Copy new lz4 patches
          cp ../kernel-patch/patches/lz4_1.10.0.patch ./common/

          cd ./common
          patch -p1 < 50_add_susfs_in_gki-android14-6.1.patch || true
          echo "SukiSU Ultra & SUSFS patches complete......"

          # 应用 LTS 分支补丁
          sudo cp -rf $GITHUB_WORKSPACE/kernel-patch/kernel-common/* ./
          echo "6.1-lts patches complete..."

          echo "Applying hooks for SukiSU..."
          cp ../../SukiSU_patch/hooks/syscall_hooks.patch ./
          patch -p1 -F 3 < syscall_hooks.patch
          echo "syscall_hooks patches complete..."

          cp ../../SukiSU_patch/69_hide_stuff.patch ./
          patch -p1 -F 3 < 69_hide_stuff.patch
          echo "69_hide_stuff patches complete..."

          cp -r ../../SukiSU_patch/other/zram/lz4k/include/linux/* ./include/linux/
          cp -r ../../SukiSU_patch/other/zram/lz4k/lib/* ./lib/
          cp -r ../../SukiSU_patch/other/zram/lz4k/crypto/* ./crypto/
          
          cp ../../SukiSU_patch/other/zram/zram_patch/6.1/lz4kd.patch ./
          patch -p1 -F 3 < lz4kd.patch || true
          echo "lz4kd patches complete..."

          files=(
              "lib/lz4/lz4_compress.c"
              "lib/lz4/lz4_decompress.c"
              "lib/lz4/lz4defs.h"
              "lib/lz4/lz4hc_compress.c"
          )

          for file in "${files[@]}"; do
              if [ -e "$file" ]; then
                  rm "$file"
              fi
          done

          patch -p1 -F 3 --fuzz=5 < lz4_1.10.0.patch || true

          if [ -f "fs/f2fs/Makefile" ]; then
              if ! grep -qF "f2fs-\$(CONFIG_F2FS_IOSTAT) += iostat.o" "fs/f2fs/Makefile"; then
                  echo "f2fs-\$(CONFIG_F2FS_IOSTAT) += iostat.o" >> "fs/f2fs/Makefile"
              fi
          fi
          echo "lz4 1.10 patches complete..."

      - name: 添加内核配置
        run: |
          CONFIG_FILE="$CONFIG/common/arch/arm64/configs/gki_defconfig"
          
          echo "Add zram configuration settings..."

          if grep -q "CONFIG_ZSMALLOC" -- "$CONFIG_FILE"; then
              sed -i 's/CONFIG_ZSMALLOC=m/CONFIG_ZSMALLOC=y/g' "$CONFIG_FILE"
          else
              echo "CONFIG_ZSMALLOC=y" >> "$CONFIG_FILE"
          fi

          sed -i 's/CONFIG_ZRAM=m/CONFIG_ZRAM=y/g' "$CONFIG_FILE"
          sed -i 's/"drivers\/block\/zram\/zram\.ko",//g; s/"mm\/zsmalloc\.ko",//g' "$CONFIG/common/modules.bzl"
          echo "CONFIG_MODULE_SIG_FORCE=n" >> "$CONFIG_FILE"

          if grep -q "CONFIG_ZSMALLOC=y" "$CONFIG_FILE" && grep -q "CONFIG_ZRAM=y" "$CONFIG_FILE"; then
            echo "CONFIG_CRYPTO_LZ4K=y" >> "$CONFIG_FILE"
            echo "CONFIG_CRYPTO_LZ4HC=y" >> "$CONFIG_FILE"
            echo "CONFIG_CRYPTO_LZ4KD=y" >> "$CONFIG_FILE"
            echo "CONFIG_ZRAM_DEF_COMP_LZ4=y" >> "$CONFIG_FILE"
            echo "CONFIG_ZRAM_WRITEBACK=y" >> "$CONFIG_FILE"
          fi
        
          echo "Add KSU configuration settings..."
          echo "CONFIG_KSU=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_MANUAL_HOOK=y" >> "$CONFIG_FILE"

          echo "Add additional tmpfs config settings..."
          echo "CONFIG_TMPFS_XATTR=y" >> "$CONFIG_FILE"
          echo "CONFIG_TMPFS_POSIX_ACL=y" >> "$CONFIG_FILE"

          echo "Add additional config settings..."
          echo "CONFIG_IP_NF_TARGET_TTL=y" >> "$CONFIG_FILE"
          echo "CONFIG_IP6_NF_TARGET_HL=y" >> "$CONFIG_FILE"
          echo "CONFIG_IP6_NF_MATCH_HL=y" >> "$CONFIG_FILE"

          echo "Add BBR config settings..."
          echo "CONFIG_TCP_CONG_ADVANCED=y" >> "$CONFIG_FILE" 
          echo "CONFIG_TCP_CONG_BBR=y" >> "$CONFIG_FILE"
          echo "CONFIG_NET_SCH_FQ=y" >> "$CONFIG_FILE"
          echo "CONFIG_TCP_CONG_BIC=n" >> "$CONFIG_FILE"
          echo "CONFIG_TCP_CONG_WESTWOOD=n" >> "$CONFIG_FILE"
          echo "CONFIG_TCP_CONG_HTCP=n" >> "$CONFIG_FILE"
          echo "CONFIG_DEFAULT_BBR=y" >> "$CONFIG_FILE"

          echo "Add SUSFS configuration settings..."
          echo "CONFIG_KSU_SUSFS=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> "$CONFIG_FILE"
    
          echo "Remove check_defconfig..."
          sed -i 's/check_defconfig//' $CONFIG/common/build.config.gki

      - name: 设置内核信息
        run: |
          cd "$CONFIG"
          SUBLEVEL=$(awk -F' = ' '/^SUBLEVEL / {print $2}' ./common/Makefile)
          if [ ! -z ${{ inputs.version }} ]; then
            echo "目标内核版本号:6.1.$SUBLEVEL-android14-11-g$BOOTHASH-${{ inputs.version }}"
            echo "BOOTNAME=6.1.$SUBLEVEL-android14-11-g$BOOTHASH-${{ inputs.version }}" >> $GITHUB_ENV
            sed -i '$s|echo "\$res"|echo "-android14-11-g'"${BOOTHASH}"'-'"${{ inputs.version }}"'"|' ./common/scripts/setlocalversion
          else
            echo "未配置内核版本号,将使用默认版本号:6.1.$SUBLEVEL-android14-11-g$BOOTHASH-lz"
            echo "BOOTNAME=6.1.$SUBLEVEL-android14-11-g$BOOTHASH-lz" >> $GITHUB_ENV
            sed -i '$s|echo "\$res"|echo "-android14-11-g'"${BOOTHASH}-lz"'"|' ./common/scripts/setlocalversion
          fi
          
          perl -pi -e 's/"\$\{LINUX_COMPILE_BY\}"/"\Q$ENV{KBUILD_BUILD_USER}\E"/g' ./common/scripts/mkcompile_h
          perl -pi -e 's/"\$\{LINUX_COMPILE_HOST\}"/"\Q$ENV{KBUILD_BUILD_HOST}\E"/g' ./common/scripts/mkcompile_h
          echo "设置内核构建用户及主机:$KBUILD_BUILD_USER@$KBUILD_BUILD_HOST"

          TIMESTAMP_ESCAPED=$(echo "$TIMESTAMP" | sed 's|/|\\/|g; s| |\\ |g')
          sed -i "s|\$(build-timestamp)|${TIMESTAMP_ESCAPED}|g" ./common/init/Makefile
          echo "设置内核构建时间:$TIMESTAMP"

          sed -i '/^[[:space:]]*"protected_exports_list"[[:space:]]*:[[:space:]]*"android\/abi_gki_protected_exports_aarch64",$/d' ./common/BUILD.bazel
          rm -rf ./common/android/abi_gki_protected_exports_*
          sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl
          sed -E -i '/^CONFIG_LOCALVERSION=/ s/(.*)"$/\1"/' ./common/arch/arm64/configs/gki_defconfig

      - name: 编译内核
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 35
          max_attempts: 3
          retry_on: timeout
          command: |
            set -e
            cd "$CONFIG"
            sed -i 's/BUILD_SYSTEM_DLKM=1/BUILD_SYSTEM_DLKM=0/' common/build.config.gki.aarch64
            sed -i '/MODULES_ORDER=android\/gki_aarch64_modules/d' common/build.config.gki.aarch64
            sed -i '/KMI_SYMBOL_LIST_STRICT_MODE/d' common/build.config.gki.aarch64
            sed -i 's/-dirty//' common/scripts/setlocalversion
            cd common
            
            # 使用 ZyC Clang 22 编译
            export PATH="$GITHUB_WORKSPACE/clang-22/bin:$PATH"
            
            # 使用 ccache 缓存加速编译
            export PATH="/usr/lib/ccache:$PATH"
            export CCACHE_COMPILERCHECK="%compiler% -dumpmachine; %compiler% -dumpversion"
            export CCACHE_NOHASHDIR="true"
            export CCACHE_HARDLINK="true"
            export CCACHE_DIR="${{ env.CCACHE_DIR }}"
            export CCACHE_MAXSIZE="8G"

            COMMON_MAKE_PARAMS=(
              -j$(nproc --all)
              O=out
              ARCH=arm64
              LLVM=1
              CROSS_COMPILE=aarch64-linux-gnu-
              CC="ccache clang"
              RUSTC=../../prebuilts/rust/linux-x86/1.73.0b/bin/rustc
              PAHOLE=../../prebuilts/kernel-build-tools/linux-x86/bin/pahole
              LD=ld.lld
              HOSTLD=ld.lld
              CONFIG_LTO_CLANG=y
              CONFIG_LTO_CLANG_THIN=y
              KCFLAGS+=-O2
            )
  
            make "${COMMON_MAKE_PARAMS[@]}" gki_defconfig || { echo "make defconfig failed"; exit 1; }
            make "${COMMON_MAKE_PARAMS[@]}" "${BUILD_TARGETS[@]}" || { echo "make failed"; exit 1; }
      
      - name: 打包编译产物
        run: |
          echo "正在打包编译产物..."
          cp ./$CONFIG/common/out/arch/arm64/boot/Image ./AnyKernel3/
          cd ./AnyKernel3
          zip -r "../$BOOTNAME.zip" ./*

      - name: 上传产出文件
        uses: actions/upload-artifact@v4
        with:
          name: SukiSU-kernel-${{ env.CONFIG }}
          path: |
            *.zip
