name: Download-Clang-21

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:

jobs:
  build-kernel-sukisu-susfs:
    runs-on: ubuntu-latest
    env:
      GOOGLE_SOURCE_URL: "https://android.googlesource.com"

    steps:
      - name: 初始化构建空间
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          swap-size-mb: 8192
          remove-dotnet: "true"
          remove-haskell: "true"
          remove-codeql: "true"

      - name: 拉取 Clang 21
        run: |
          mkdir kernel-clang && cd kernel-clang
          git init
          git remote add origin $GOOGLE_SOURCE_URL/platform/prebuilts/clang/host/linux-x86/
          git config core.sparseCheckout true
          echo "main-kernel/clang-r563880/*" > .git/info/sparse-checkout
          git pull --depth=1 origin main-kernel