name: Download-Clang-21

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:

jobs:
  build-kernel-sukisu-susfs:
    runs-on: ubuntu-latest
    env:
      GOOGLE_SOURCE_URL: "https://android.googlesource.com"

    steps:
      - name: 初始化构建空间
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          swap-size-mb: 8192
          remove-dotnet: "true"
          remove-haskell: "true"
          remove-codeql: "true"

      - name: 拉取内核源码
        run: |
          mkdir -p ./git-repo
          curl https://storage.googleapis.com/git-repo-downloads/repo > ./git-repo/repo
          chmod a+rx ./git-repo/repo
          mkdir -p "$CONFIG"
          cd "$CONFIG"
          $GITHUB_WORKSPACE/./git-repo/repo init --depth=1 -u https://${{ secrets.PATCH_ACCESS_TOKEN }}@github.com/OgayCn/Kernel-Patch.git -b refs/heads/main -m SM8650_Custom.xml
          $GITHUB_WORKSPACE/./git-repo/repo --trace sync -c -j$(nproc --all) --no-tags --fail-fast